### ISSUE TITLE
バックエンドAPIをデプロイする。

### ISSUE THREAD

**Issue by kagami-tsukimura** [kagami-tsukimura/room-booking#1]
FastAPIで作成したバックエンドをデプロイする。

**Comment by k-shimura7617** [comment]
無料でバックエンドにデプロイしたい。
- **Deta**
  - 実用性があり無料はほぼ一択。

**Comment by k-shimura7617** [comment]
Deta SpaceはUIが大きく変更されたため調査。

[Deta Cloud→Deta Space](https://qiita.com/kakiuchis/items/80f6239f6319066ee18d#space-pushweb%E5%85%AC%E9%96%8B)

**Comment by k-shimura7617** [comment]
お試しでデプロイ

[Deta Space](https://deta.space/)

**Comment by k-shimura7617** [comment]
相対パスでエラー？
loggerで確認。

**Comment by k-shimura7617** [comment]
[BackEnd](https://booking-1-x3709405.deta.app/)

一旦デプロイは完了。
commitしてプルリク出す。
