### ISSUE TITLE
バックエンドのルートメッセージを改修する。

### ISSUE THREAD

**Issue by kagami-tsukimura** [kagami-tsukimura/room-booking#24]
GitHubにAPIも公開しているが、ルートのメッセージが適していない。

**Comment by k-shimura7617** [comment]
バックエンド

- ルートのメッセージを "Welcome to room-booking API!" とかに変えておく。
  - 変えたらpushする。
- pushしたら以下。

**Comment by k-shimura7617** [comment]
```bash
  space push
  ```
  - 動作確認（ルート）
